# Generated by Django 5.2.13 on 2026-05-04 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rendered_at", models.DateTimeField(auto_now_add=True)),
                ("rendered_by", models.CharField(blank=True, max_length=128)),
                ("template_name", models.CharField(max_length=128)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("git_commit_sha", models.CharField(blank=True, max_length=40)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="inventory.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-rendered_at"],
            },
        ),
        migrations.CreateModel(
            name="ZtpEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serial_number", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dhcp_request", "DHCP request"),
                            ("bootfile_fetch", "Bootfile fetched"),
                            ("config_fetch", "Config fetched"),
                            ("image_fetch", "Image fetched"),
                            ("ready", "Device reported ready"),
                            ("failed", "Device reported failure"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ztp_events",
                        to="inventory.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["serial_number", "kind"],
                        name="ztp_ztpeven_serial__7855df_idx",
                    )
                ],
            },
        ),
    ]
