# Generated by Django 5.2.13 on 2026-05-04 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. NCS-540-ACC-SYS, ASR-9901", max_length=64
                    ),
                ),
                (
                    "target_software_version",
                    models.CharField(
                        blank=True,
                        help_text="Desired image version. ZTP will upgrade if device version is older.",
                        max_length=64,
                    ),
                ),
                (
                    "software_image_filename",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
            options={
                "ordering": ["vendor__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Short site code, e.g. mpls-01",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("region", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "driver_key",
                    models.SlugField(
                        help_text="Identifier matching apps.integrations.devices driver registry (e.g. 'cisco_iosxr', 'juniper_junos', 'arista_eos').",
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "hostname",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered (in lab)"),
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("config_generated", "Config generated"),
                            ("provisioning", "Provisioning (ZTP in progress)"),
                            ("ready", "Ready (config loaded)"),
                            ("deployed", "Deployed to prod"),
                            ("failed", "Failed"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        db_index=True,
                        default="discovered",
                        max_length=32,
                    ),
                ),
                ("console_server", models.CharField(blank=True, max_length=128)),
                ("console_port", models.CharField(blank=True, max_length=32)),
                (
                    "staging_mac",
                    models.CharField(
                        blank=True, help_text="From DHCP lease.", max_length=17
                    ),
                ),
                ("staging_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("staging_seen_at", models.DateTimeField(blank=True, null=True)),
                ("loopback0", models.GenericIPAddressField(blank=True, null=True)),
                ("mgmt_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("reservation_note", models.CharField(blank=True, max_length=255)),
                ("last_ztp_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_ztp_event", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "reserved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserved_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="inventory.deploymentscenario",
                    ),
                ),
                (
                    "device_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="inventory.devicemodel",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="inventory.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deploymentscenario",
            name="device_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="inventory.devicemodel",
            ),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="inventory.vendor",
            ),
        ),
        migrations.CreateModel(
            name="DeviceInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. HundredGigE0/0/0/0", max_length=64
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uplink", "Uplink"),
                            ("core", "Core"),
                            ("peer", "Peer"),
                            ("customer", "Customer"),
                            ("mgmt", "Management"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "ipv4_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                (
                    "ipv4_prefix_length",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ipv6_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv6"
                    ),
                ),
                (
                    "ipv6_prefix_length",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bluecat_object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="inventory.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device", "name"],
                "unique_together": {("device", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="devicemodel",
            unique_together={("vendor", "name")},
        ),
    ]
